[git_fixup]
file = "git_fixup.yml"

[todo_check]
file = "todo_check.yml"

[python_black]
file = "python_black.yml"
language = "python"

[python_mypy]
file = ["python_mypy.yml", "mypy-problem-matcher.json"]
language = "python"

[cpp_format]
file = "cpp_format.yml"
language = "c++"
